// `.env.ts` is generated by the `npm run env` command
import env from '@env/.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  //serverUrl: 'http://igrwapo03:8080',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    // 'fr-FR',
    'es-MX'
  ]
};

export enum serverUrl {
  apodaca = 'http://igrwapo03:8080',
  elizabethtown = 'http://metuselzwweb01',
  saltillo = 'http://METMXSLTWACT01',
  eltalar = 'http://igrwapo03:8080',
  osasco = 'http://igrwapo03:8080',
  slp = 'http://igrwslp01'
}
