
export const env = "production"
const baseUrl = {apo: "https://sfms.metalsa.com",
                et: "https://sfms-et.metalsa.com", 
                testing: "http://i40appmasterqa.westus.cloudapp.azure.com", 
                local: "http://localhost:1337"}
const envs = {
    apo: {baseUrl: baseUrl.apo, wsUrl: (baseUrl.apo +":9999"), andonUrl: (baseUrl.apo + "/showroom-sa-chrome/build") },
    et: {baseUrl: baseUrl.et, wsUrl: (baseUrl.et +":9999"), andonUrl: (baseUrl.et + "/showroom-sa-chrome/build") },
    testing: {baseUrl: baseUrl.testing, wsUrl: (baseUrl.testing +":9999")},
    local: {baseUrl: baseUrl.local, wsUrl: (baseUrl.testing +":9999"), andonUrl: (baseUrl.testing + "/showroom-sa-chrome/build") },
} 
const config = {    
    development: {
        baseUrl: baseUrl.local,
        apo_schulerA: envs.local,
        apo_schulerB: envs.local,
        apo_fagorA: envs.local,
        apo_fagorB: envs.local,
        apo_k1200: envs.local,
        apo_jinan: envs.local,
        apo_e1500: envs.local,
        apo_aida: envs.local,
        apo_d800: envs.local,
        et_k1: envs.local,
        et_k2: envs.local,
        et_k3: envs.local,
        et_k4: envs.local,
        et_k5: envs.local,
        et_k6: envs.local,
        et_k7: envs.local,
        et_k8: envs.local,
        et_k9: envs.local,
        et_k14: envs.local,
        et_k15: envs.local,
        env: 'development'
    },
    testing: {
        baseUrl: baseUrl.testing,
        apo_schulerA: envs.testing,
        apo_schulerB: envs.testing,
        apo_fagorA: envs.testing,
        apo_fagorB: envs.testing,
        apo_k1200: envs.testing,
        apo_jinan: envs.testing,
        apo_e1500: envs.testing,
        apo_aida: envs.testing,
        apo_d800: envs.testing,
        et_k1: envs.testing,
        et_k2: envs.testing,
        et_k3: envs.testing,
        et_k4: envs.testing,
        et_k5: envs.testing,
        et_k6: envs.testing,
        et_k7: envs.testing,
        et_k8: envs.testing,
        et_k9: envs.testing,
        et_k14: envs.testing,
        et_k15: envs.testing,
        env: 'testing'
    },
    mtesting: {
        baseUrl: baseUrl.testing,
        apo_schulerA: envs.testing,
        apo_schulerB: envs.testing,
        apo_fagorA: envs.testing,
        apo_fagorB: envs.testing,
        apo_k1200: envs.testing,
        apo_jinan: envs.testing,
        apo_e1500: envs.testing,
        apo_aida: envs.testing,
        apo_d800: envs.testing,
        et_k1: envs.testing,
        et_k2: envs.testing,
        et_k3: envs.testing,
        et_k4: envs.testing,
        et_k5: envs.testing,
        et_k6: envs.testing,
        et_k7: envs.testing,
        et_k8: envs.testing,
        et_k9: envs.testing,
        et_k14: envs.testing,
        et_k15: envs.testing,
        env: 'mtesting'
    },
    etesting: {
        baseUrl: baseUrl.et,
        apo_schulerA: envs.et,
        apo_schulerB: envs.et,
        apo_fagorA: envs.et,
        apo_fagorB: envs.et,
        apo_k1200: envs.et,
        apo_jinan: envs.et,
        apo_e1500: envs.et,
        apo_aida: envs.et,
        apo_d800: envs.et,
        et_k1: envs.et,
        et_k2: envs.et,
        et_k3: envs.et,
        et_k4: envs.et,
        et_k5: envs.et,
        et_k6: envs.et,
        et_k7: envs.et,
        et_k8: envs.et,
        et_k9: envs.et,
        et_k14: envs.et,
        et_k15: envs.et,
        env: 'etesting'
    },
    production: {
        baseUrl: baseUrl.apo,
        apo_schulerA: envs.apo,
        apo_schulerB: envs.apo,
        apo_fagorA: envs.apo,
        apo_fagorB: envs.apo,
        apo_k1200: envs.apo,
        apo_jinan: envs.apo,
        apo_e1500: envs.apo,
        apo_aida: envs.apo,
        apo_d800: envs.apo,
        et_k1: envs.et,
        et_k2: envs.et,
        et_k3: envs.et,
        et_k4: envs.et,
        et_k5: envs.et,
        et_k6: envs.et,
        et_k7: envs.et,
        et_k8: envs.et,
        et_k9: envs.et,
        et_k14: envs.et,
        et_k15: envs.et,
        env: 'production'
    }
}

export default config