/*
    Login Screen
    ../screens/login/actions.js
*/
export const SET_PUSH_TOKEN = 'SET_PUSH_TOKEN'
export const DISPLAY_AUTH_ERROR = 'DISPLAY_AUTH_ERROR'
export const SET_SESSION_DATA = 'SET_SESSION_DATA'
export const CLEAR_SESSION_DATA = 'CLEAR_SESSION_DATA'
export const SET_APP_DOMAIN = 'SET_APP_DOMAIN'
export const SET_ORIENTATION = 'SET_ORIENTATION'
export const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES'

/*
    Home Screen
    ../screens/home/actions.js
*/
export const CHECK_IN = 'CHECK_IN'
export const CHECK_OUT = 'CHECK_OUT'
export const CHECK_OUT_FULL = 'CHECK_OUT_FULL'
export const SET_CURRENT_FAILURE = 'SET_CURRENT_FAILURE'
export const SET_CURRENT_REPORT = 'SET_CURRENT_REPORT'
export const SET_CURRENT_ESCALATION = 'SET_CURRENT_ESCALATION'
export const CLEAR_CURRENT_FAILURE = 'CLEAR_CURRENT_FAILURE'
export const SET_CURRENT_PERIOD_DOWNTIME = 'SET_CURRENT_PERIOD_DOWNTIME'
export const SET_TOOL_SPEED = 'SET_TOOL_SPEED'
export const SET_PRODUCTION = 'SET_PRODUCTION'
export const SET_CURRENT_SHIFT_LOG = 'SET_CURRENT_SHIFT_LOG'
export const RELOAD_PRODUCTION = 'RELOAD_PRODUCTION'
export const RELOAD_SHIFT = 'RELOAD_SHIFT'
export const SET_CURRENT_TOOL = 'SET_CURRENT_TOOL'

/*
    Last Shift Log
    ../screens/lastShiftLog/actions.js
*/
export const SET_LAST_SHIFT_LOG = 'SET_LAST_SHIFT_LOG'
export const SET_LAST_SHIFT_RANGE = 'SET_LAST_SHIFT_RANGE'
export const SET_LAST_SHIFT_DATE = 'SET_LAST_SHIFT_DATE'

/*
    Checklist
    ../screens/checklist/actions.js
*/
export const CHEKLIST_ANSWERS_SAVED = 'CHEKLIST_ANSWERS_SAVED'
export const DISPLAY_CHECKLIST_ERROR = 'DISPLAY_CHECKLIST_ERROR'
export const SET_INITIAL_CHECKLIST = 'SET_INITIAL_CHECKLIST'
export const SET_SAFETY_DEVICES_CHECKLIST = 'SET_SAFETY_DEVICES_CHECKLIST'
export const CLEAR_CHECKLIST_ANSWERS = 'CLEAR_CHECKLIST_ANSWERS'
export const SET_CURRENT_CHECK = 'SET_CURRENT_CHECK'
export const SET_EXTERNAL_CHECKLIST = 'SET_EXTERNAL_CHECKLIST'

/*
    Report
    ../screens/report/actions.js
*/
export const SET_ISSUE_TYPES = 'SET_ISSUE_TYPES'
export const DISPLAY_ERROR = 'DISPLAY_ERROR'
export const SELECT_ISSUE_TYPE = 'SELECT_ISSUE_TYPE'
export const DESELECT_ISSUE_TYPE = 'DESELECT_ISSUE_TYPE'
export const SHOW_SUCCESSFUL_MESSAGE = 'SHOW_SUCCESSFUL_MESSAGE'
export const SET_ISSUES = 'SET_ISSUES'
export const FAILURE_IDENTIFIED = 'FAILURE_IDENTIFIED'
export const SET_ABNORNALITY_COMMENT = 'SET_ABNORNALITY_COMMENT'
export const SELECT_SINGLE_ISSUE = 'SELECT_SINGLE_ISSUE'

/*
    Profile
    ../screens/profile/actions.js
*/
export const SET_KPIS = 'SET_KPIS'
export const SET_KPIS_DATE = 'SET_KPIS_DATE'

/*
    ToolList
    ../screens/toolList/actions.js
*/
export const SET_TOOL_LIST = 'SET_TOOL_LIST'


/*
    ToolDetail
    ../screens/tooldetail/actions.js
*/
export const SET_TOOL_REPORTS = 'SET_TOOL_REPORTS'
export const SET_ALL_TOOLS = 'SET_ALL_TOOLS'
export const SET_DAILY_REPORT = 'SET_DAILY_REPORT'
export const SET_DOWNTIMES = 'SET_DOWNTIMES'
export const SET_DOWNTIME = 'SET_DOWNTIME'
export const CLEAR_DOWNTIMES = 'CLEAR_DOWNTIMES'

/*
    Process Parameter
    ../screens/processParameter/actions.js
*/
export const SET_PROCESS_PARAMETER_ERROR = 'SET_PROCESS_PARAMETER_ERROR';
export const SET_PROCESS_OBJECTIVES = 'SET_PROCESS_OBJECTIVES';
export const SET_PROCESS_OBJECTIVES_REAL_VALUE = 'SET_PROCESS_OBJECTIVES_REAL_VALUE';


/*
    Quality Imspection Sheet
    ../screens/qualityInspection/actions.js
*/
export const SET_QUALITY_TOOLS = 'SET_QUALITY_TOOLS';
export const SET_QUALITY_INSPECTION_LIST = 'SET_QUALITY_INSPECTION_LIST';
export const SET_QUALITY_CHECKLIST_TRENDS = 'SET_QUALITY_CHECKLIST_TRENDS';
export const SET_QUALITY_INSPECTION_SHEET = 'SET_QUALITY_INSPECTION_SHEET';
export const SET_QUALITY_INSPECTION_ERROR = 'SET_QUALITY_INSPECTION_ERROR';
export const SET_QUALITY_TOOL_TRENDS = 'SET_QUALITY_TOOL_TRENDS';
export const SET_QUALITY_WORK_ORDERS = 'SET_QUALITY_WORK_ORDERS';
export const SET_QUALITY_REPORT = 'SET_QUALITY_REPORT';
export const SEARCH_TOOLS = 'SEARCH_TOOLS';
export const GET_QUALITY_TREND_REPORT = 'GET_QUALITY_TREND_REPORT';
export const GET_ACTUAL_TREND = 'GET_ACTUAL_TREND';
export const SET_JULIAN_NUMBERS = 'SET_JULIAN_NUMBERS';

/*
    FailureComments
    ../screens/failure/actions.js
*/
export const SET_ALL_COMMENTS = 'SET_ALL_COMMENTS'
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS'
export const SET_FAILURE_LOG = 'SET_FAILURE_LOG'
export const SET_ASSISTANCE_USER = 'SET_ASSISTANCE_USER'
export const CLEAR_ASSISTANCE_USER = 'CLEAR_ASSISTANCE_USER'
export const SET_DOWNTIME_HISTORIC = 'SET_DOWNTIME_HISTORIC'
export const SET_REPORT = 'SET_REPORT'

export const SET_NEXT_TOOL = "SET_NEXT_TOOL";
export const SET_TOOL_PARAMS = "SET_TOOL_PARAMS";
export const SET_CURRENT_PROD = "SET_CURRENT_PROD";

export const EXTERNAL_CHECKLIST_READY = "EXTERNAL_CHECKLIST_READY";
export const TOOL_INFO_READY = "TOOL_INFO_READY";
export const SET_PRODUCTION_ERROR = "SET_PRODUCTION_ERROR";
export const PRODUCTION_PREPARED = "PRODUCTION_PREPARED";
export const PRODUCTION_VALIDATED = "PRODUCTION_VALIDATED";
export const SET_CURRENT_PRODUCTION = "SET_CURRENT_PRODUCTION";
export const PRODUCTION_CLOSED = "PRODUCTION_CLOSED";
export const SET_LAST_PRODUCTION = "SET_LAST_PRODUCTION";
export const SET_DAILY_REPORT_LOG = "SET_DAILY_REPORT_LOG";
export const PRODUCTION_VERIFIED = "PRODUCTION_VERIFIED";
export const CHECKLIST_VALIDATED = "CHECKLIST_VALIDATED";

/*
    Tryout
    ../screens/tryout/actions.js
*/
export const DISPLAY_ERROR_OUTS = 'DISPLAY_ERROR_OUTS'
export const SET_ISSUES_OUTS = 'SET_ISSUES_OUTS'
export const SELECT_SINGLE_ISSUE_OUTS = 'SELECT_SINGLE_ISSUE_OUTS'
export const SET_ASSISTANCE_USER_OUTS = 'SET_ASSISTANCE_USER_OUTS'
//Workorders Maximo
export const SET_WORKORDERS_MAXIMO = "SET_WORKORDERS_MAXIMO";
export const WORK_ORDER_MAXIMO_CREATED = "WORK_ORDER_MAXIMO_CREATED";
export const WORK_ORDER_MAXIMO_UPDATED = "WORK_ORDER_MAXIMO_UPDATED";
export const WORK_ORDER_MAXIMO_CREATED_SFMS = "WORK_ORDER_MAXIMO_CREATED_SFMS";
export const WORK_ORDER_MAXIMO_UPDATED_SFMS = "WORK_ORDER_MAXIMO_UPDATED_SFMS";
export const WORK_ORDER_MAXIMO_EXISTS_SFMS = "WORK_ORDER_MAXIMO_EXISTS_SFMS";
export const CURRENT_DOWNTIME_TOOL = "CURRENT_DOWNTIME_TOOL";
