dojo.require("dojox.validate"); 				/*SOLICITANDO LAS ACCIONES DE VALIDACION DE DOJO*/
dojo.require("dijit.form.ValidationTextBox");	/*SOLICITANDO LAS ACCIONES DE VALIDACION DE DOJO PARA CAJAS DE TEXTO*/
dojo.require("dijit.form.DateTextBox");			/*SOLICITANDO LAS ACCIONES Y COMPLEMENTOS DE DATEPICKER [COMBO BOX DE LA FECHA]*/
dojo.require("dojox.validate.web");				/*SOLICITANDO LAS ACCIONES DE VALIDACION DE DOJO PARA WEB'S Y CORREOS ELECTRONICOS*/

